### ISSUE TITLE
delete command does not work 

### ISSUE THREAD

**Issue by mcdoeswhat** [AcmeProject/WildernessTp#16]
[19:57:30 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'wildtp' in plugin Wild v1.48
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.2-R0.1-SNAPSHOT-b1444.jar:git-Spigot-d21162c-82f3b02]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.2-R0.1-SNAPSHOT-b1444.jar:git-Spigot-d21162c-82f3b02]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:651) ~[spigot-1.12.2-R0.1-SNAPSHOT-b1444.jar:git-Spigot-d21162c-82f3b02]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [spigot-1.12.2-R0.1-SNAPSHOT-b1444.jar:git-Spigot-d21162c-82f3b02]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot-1.12.2-R0.1-SNAPSHOT-b1444.jar:git-Spigot-d21162c-82f3b02]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.2-R0.1-SNAPSHOT-b1444.jar:git-Spigot-d21162c-82f3b02]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.2-R0.1-SNAPSHOT-b1444.jar:git-Spigot-d21162c-82f3b02]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2-R0.1-SNAPSHOT-b1444.jar:git-Spigot-d21162c-82f3b02]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_162]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_162]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2-R0.1-SNAPSHOT-b1444.jar:git-Spigot-d21162c-82f3b02]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2-R0.1-SNAPSHOT-b1444.jar:git-Spigot-d21162c-82f3b02]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2-R0.1-SNAPSHOT-b1444.jar:git-Spigot-d21162c-82f3b02]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2-R0.1-SNAPSHOT-b1444.jar:git-Spigot-d21162c-82f3b02]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2-R0.1-SNAPSHOT-b1444.jar:git-Spigot-d21162c-82f3b02]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_162]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
        at net.poweredbyhate.wildtp.AdminsGoneWild.onCommand(AdminsGoneWild.java:61) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.2-R0.1-SNAPSHOT-b1444.jar:git-Spigot-d21162c-82f3b02]
        ... 15 more

**Comment by RoboMWM** [comment]
missing portals.yml as well as the command you ran.

**Comment by RoboMWM** [comment]
Fixed, but you made an error in your command
