### ISSUE TITLE
Console spam on "drop from above"

### ISSUE THREAD

**Issue by kemmeo** [AcmeProject/WildernessTp#17]
Seems like the way you make players invaluable is classing with AAC

```
13.06 12:49:55 [Server] ERROR Could not pass event BlurredBlockBreakEvent to AAC v3.3.15
13.06 12:49:55 [Server] INFO org.bukkit.event.EventException: null
13.06 12:49:55 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1443]
13.06 12:49:55 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.2.jar:git-Paper-1443]
13.06 12:49:55 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1443]
13.06 12:49:55 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[patched_1.12.2.jar:git-Paper-1443]
13.06 12:49:55 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[patched_1.12.2.jar:git-Paper-1443]
13.06 12:49:55 [Server] INFO at net.poweredbyhate.wildtp.TeleportGoneWild.n0tAGreifClam(TeleportGoneWild.java:203) ~[WildTP.jar:?]
13.06 12:49:55 [Server] INFO at net.poweredbyhate.wildtp.TeleportGoneWild.getRandomeLocation(TeleportGoneWild.java:158) ~[WildTP.jar:?]
13.06 12:49:55 [Server] INFO at net.poweredbyhate.wildtp.TeleportGoneWild.realTeleportt(TeleportGoneWild.java:99) ~[WildTP.jar:?]
13.06 12:49:55 [Server] INFO at net.poweredbyhate.wildtp.TeleportGoneWild.WildTeleport(TeleportGoneWild.java:52) ~[WildTP.jar:?]
13.06 12:49:55 [Server] INFO at net.poweredbyhate.wildtp.CommandsGoneWild.onCommand(CommandsGoneWild.java:27) ~[WildTP.jar:?]
13.06 12:49:55 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1443]
13.06 12:49:55 [Server] INFO at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:550) ~[CMI.jar:?]
13.06 12:49:55 [Server] INFO at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:510) ~[CMI.jar:?]
13.06 12:49:55 [Server] INFO at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:107) ~[CMI.jar:?]
13.06 12:49:55 [Server] INFO at com.Zrips.CMI.Modules.Portals.CMIPortal.teleport(CMIPortal.java:98) ~[CMI.jar:?]
13.06 12:49:55 [Server] INFO at com.Zrips.CMI.Modules.Portals.PortalListener.onPlayerMove(PortalListener.java:118) ~[CMI.jar:?]
13.06 12:49:55 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor465.execute(Unknown Source) ~[?:?]
13.06 12:49:55 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1443]
13.06 12:49:55 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.2.jar:git-Paper-1443]
13.06 12:49:55 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1443]
13.06 12:49:55 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[patched_1.12.2.jar:git-Paper-1443]
13.06 12:49:55 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[patched_1.12.2.jar:git-Paper-1443]
13.06 12:49:55 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:692) ~[patched_1.12.2.jar:git-Paper-1443]
13.06 12:49:55 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126) ~[patched_1.12.2.jar:git-Paper-1443]
13.06 12:49:55 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) ~[patched_1.12.2.jar:git-Paper-1443]
13.06 12:49:55 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1443]
13.06 12:49:55 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
13.06 12:49:55 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
13.06 12:49:55 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1443]
13.06 12:49:55 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1443]
13.06 12:49:55 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1443]
13.06 12:49:55 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1443]
13.06 12:49:55 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1443]
13.06 12:49:55 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
13.06 12:49:55 [Server] INFO Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@86a09df
13.06 12:49:55 [Server] INFO at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source) ~[?:?]
13.06 12:49:55 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
13.06 12:49:55 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
13.06 12:49:55 [Server] INFO at me.konsolas.aac.be.a(be.java:36) ~[AAC.jar:3.3.15]
13.06 12:49:55 [Server] INFO at me.konsolas.aac.be.b(be.java:6) ~[AAC.jar:3.3.15]
13.06 12:49:55 [Server] INFO at me.konsolas.aac.cc.a(cc.java:7) ~[AAC.jar:3.3.15]
13.06 12:49:55 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor530.execute(Unknown Source) ~[?:?]
13.06 12:49:55 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1443]
13.06 12:49:55 [Server] INFO ... 33 more
13.06 12:49:55 [Server] ERROR Could not pass event BlurredBlockBreakEvent to AAC v3.3.15
13.06 12:49:55 [Server] INFO org.bukkit.event.EventException: null
13.06 12:49:55 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1443]
13.06 12:49:55 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.2.jar:git-Paper-1443]
13.06 12:49:55 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1443]
13.06 12:49:55 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) [patched_1.12.2.jar:git-Paper-1443]
13.06 12:49:55 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) [patched_1.12.2.jar:git-Paper-1443]
13.06 12:49:55 [Server] INFO at net.poweredbyhate.wildtp.TeleportGoneWild.n0tAGreifClam(TeleportGoneWild.java:203) [WildTP.jar:?]
13.06 12:49:55 [Server] INFO at net.poweredbyhate.wildtp.TeleportGoneWild.getRandomeLocation(TeleportGoneWild.java:158) [WildTP.jar:?]
13.06 12:49:55 [Server] INFO at net.poweredbyhate.wildtp.TeleportGoneWild$4.run(TeleportGoneWild.java:286) [WildTP.jar:?]
13.06 12:49:55 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) [patched_1.12.2.jar:git-Paper-1443]
13.06 12:49:55 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) [patched_1.12.2.jar:git-Paper-1443]
13.06 12:49:55 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [patched_1.12.2.jar:git-Paper-1443]
13.06 12:49:55 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1443]
13.06 12:49:55 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1443]
13.06 12:49:55 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1443]
13.06 12:49:55 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
13.06 12:49:55 [Server] INFO Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@31ff111f
13.06 12:49:55 [Server] INFO at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source) ~[?:?]
13.06 12:49:55 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
13.06 12:49:55 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
13.06 12:49:55 [Server] INFO at me.konsolas.aac.be.a(be.java:36) ~[AAC.jar:3.3.15]
13.06 12:49:55 [Server] INFO at me.konsolas.aac.be.b(be.java:6) ~[AAC.jar:3.3.15]
13.06 12:49:55 [Server] INFO at me.konsolas.aac.cc.a(cc.java:7) ~[AAC.jar:3.3.15]
13.06 12:49:55 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor530.execute(Unknown Source) ~[?:?]
13.06 12:49:55 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1443]
13.06 12:49:55 [Server] INFO ... 14 more
```

**Comment by RoboMWM** [comment]
use three backticks for code blocks instead of one.

I've edited the above

**Comment by kemmeo** [comment]
Very sorry, thanks for letting me know.

**Comment by RoboMWM** [comment]
Now, I'm unable to see why this is happening or what in the world AAC is trying to do, because their code is obfuscated nor open source. (And no, I don't think anticheats should be closed source and obfuscated, since you're effectively relying on hidden traps if such is really necessary. Honeypots and related traps are cheat _detectors_ and thus help identify cheaters instead of being anti (preventing) cheats.)

They have also demonstrated refusal to support the usage of player metadata to exempt players (NCP allows for this, in addition to permissions and within its API).https://github.com/konsolas/AAC-Issues/issues/948

It'll be up to them to either provide or explain the relevant code. Until then, there's nothing I can do. They can discuss here or you can link and report there.

`Personally, I recommend just using NCP.`

**Comment by RoboMWM** [comment]
As for this particular error, no idea what AAC is doing. Other than the fact that AAC has been known to be worse than NCP especially in regards to major issues, closed source anticheat plugins are no better (and in fact worse, since no PRs can be made) than open source ones.

The only time closed source would make sense is to obscure "active traps/honeypots." And I just realized I'm repeating myself.

Using permissions adds a bit of overhead, and definitely more code. I can't recall the entire process, but I'd have to create a PermissionAttachment or similar, add such permissions, add them to player, etc. It's not as simple as adding and removing new metadata to a player. If anyone wants to PR that I guess they could, but ideally would like to only have it only perform if it detects AAC to be installed.
