### ISSUE TITLE
Console errors when players have insufficient funds.

### ISSUE THREAD

**Issue by axemwa** [AcmeProject/WildernessTp#18]
Console is throwing errors when a player doesn't have enough funds to use the /wild command whether it's attempted via player or console these errors appear only at those times

When attempted by the player:

https://hastebin.com/ofawigulet.vbs

When attempted by console:

https://hastebin.com/ososudisoc.vbs

**Comment by RoboMWM** [comment]
One thing I don't like about hastebin is that pastes expire.

Checked code, don't see how it would error so yea don't recall the issue either :c

**Comment by axemwa** [comment]
sorry i don't usually use hastebin don't know why I did this time, I'll send a vid of how the error occurs.

**Comment by RoboMWM** [comment]
No need for video. I prefer hastebin but the expiry is annoying. Just paste it again in gist or directly in here with backticks.


    ```
    like so
    ```

**Comment by axemwa** [comment]
Sorry about that I don't like hastebin either, I usually use pastebin would that suffice for a lot of error codes?

**Comment by RoboMWM** [comment]
pastebin is the worst, ad-ridden and bloated for pastes.

**Comment by RoboMWM** [comment]
Just paste in here directly

**Comment by axemwa** [comment]
k no probs

**Comment by axemwa** [comment]
[16:50:32 INFO]: Shano_dekono issued server command: /rtp [16:50:32 ERROR]: Could not pass event PreWildTeleportEvent to Wild v1.48 org.bukkit.event.EventException: null at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1555] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1555] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1555] at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[patched_1.12.2.jar:git-Paper-1555] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[patched_1.12.2.jar:git-Paper-1555] at net.poweredbyhate.wildtp.TeleportGoneWild.realTeleportt(TeleportGoneWild.java:110) ~[?:?] at net.poweredbyhate.wildtp.TeleportGoneWild.WildTeleport(TeleportGoneWild.java:52) ~[?:?] at net.poweredbyhate.wildtp.CommandsGoneWild.onCommand(CommandsGoneWild.java:75) ~[?:?] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1555] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.12.2.jar:git-Paper-1555] at gyurix.commands.CustomCommandMap.dispatch(CustomCommandMap.java:82) ~[?:?] at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[patched_1.12.2.jar:git-Paper-1555] at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1476) ~[patched_1.12.2.jar:git-Paper-1555] at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1281) ~[patched_1.12.2.jar:git-Paper-1555] at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-1555] at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-1555] at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1555] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_172] at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_172] at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1555] at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1555] at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1555] at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1555] at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1555] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172] Caused by: java.lang.NullPointerException at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:324) ~[patched_1.12.2.jar:git-Paper-1555] at net.poweredbyhate.wildtp.TooWildForEnums.translate(TooWildForEnums.java:85) ~[?:?] at net.poweredbyhate.wildtp.PreTeleportEvent.onPreTeleport(PreTeleportEvent.java:18) ~[?:?] at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor632.execute(Unknown Source) ~[?:?] at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1555] ... 24 more

**Comment by lhdev** [comment]
I am seeing the same issue on 1.13.1, I'll fire up the test server and get you an output from a Spigot 1.13.1 server.

**Comment by RoboMWM** [comment]
@axemwa copy from your logs, not from console/panel please. Your paste lacks newlines.

**Comment by RoboMWM** [comment]
This is caused by missing a message for the no money message key tho.

**Comment by lhdev** [comment]
What's the key? 
This is my Messages.yml

```
NO_PERMS: '&4You do not have permission!'
NO_SIGN_PERMS: '&4You do not have permission to make a wild sign'
NO_BREAK: '&4Hey! You can not break WildTp sign!'
NO_LOCATION: '&4No suitable locations found.'
NO_BIOME: '&4You may not put signs in %BIOME%'
YES_SIGN: '&aSuccessfully made a new WildTP sign'
BREAK_SIGN: '&aYou have broken a WildTP sign'
COOLDOWN: '&4You must wait %TIME% seconds until you can use the command/sign again'
RELOADED: '&aPlugin config has successfuly been reloaded.'
WAIT_MSG: '&6Teleporting in {wait} seconds'
DIDNT_WAIT: '&cYou need to hold still while you wait!'
NO_WE: '&cWorldEdit must be installed for this command.'
```

**Comment by RoboMWM** [comment]
`NO_MONEY`

**Comment by lhdev** [comment]
Excellent!  Is there a variable to display the funds required?  Like %COST% or something?

**Comment by axemwa** [comment]
ok sorry, did u still want me to send you the latest log or nvm since it looks like you worked it out?

**Comment by lhdev** [comment]
It's not the key that's the issue...

```
[22:25:12] [Server thread/ERROR]: Could not pass event PreWildTeleportEvent to Wild v1.48
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
        at net.poweredbyhate.wildtp.TeleportGoneWild.realTeleportt(TeleportGoneWild.java:110) ~[?:?]
        at net.poweredbyhate.wildtp.TeleportGoneWild.WildTeleport(TeleportGoneWild.java:52) ~[?:?]
        at net.poweredbyhate.wildtp.CommandsGoneWild.onCommand(CommandsGoneWild.java:75) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:695) ~[spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1644) ~[spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1479) ~[spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:411) [spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
        at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:324) ~[spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
        at net.poweredbyhate.wildtp.TooWildForEnums.translate(TooWildForEnums.java:85) ~[?:?]
        at net.poweredbyhate.wildtp.PreTeleportEvent.onPreTeleport(PreTeleportEvent.java:18) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
        ... 22 more
```

I've added the following to Messages.yml
```
NO_MONEY: '&cSorry, you have insufficient funds.'
```

**Comment by RoboMWM** [comment]
closed cuz I already added it to defaults. If you still want a variable just make another issue. Ya I just did my best to find the line in your paste lol, thanks tho

**Comment by RoboMWM** [comment]
o, ya needs to be set too, heh. So you'll need to wait for update for this to work properly. Mmm we all have a little cue ball
