### ISSUE TITLE
After testing the latest wildtp in 1.13.1 teleport a few times an error came up, possible compatibility issue with InventoryFullPlus plugin... fixable?

### ISSUE THREAD

**Issue by axemwa** [AcmeProject/WildernessTp#23]
[17:36:18 ERROR]: Could not pass event BlurredBlockBreakEvent to InventoryFullPlus v2.4.1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.1.jar:git-Paper-346]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.1.jar:git-Paper-346]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.1.jar:git-Paper-346]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.1.jar:git-Paper-346]
        at net.poweredbyhate.wildtp.TeleportGoneWild.n0tAGreifClam(TeleportGoneWild.java:243) ~[?:?]
        at net.poweredbyhate.wildtp.TeleportGoneWild.chekar(TeleportGoneWild.java:199) ~[?:?]
        at net.poweredbyhate.wildtp.TeleportGoneWild$1$1.call(TeleportGoneWild.java:157) ~[?:?]
        at net.poweredbyhate.wildtp.TeleportGoneWild$1$1.call(TeleportGoneWild.java:153) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftFuture.run(CraftFuture.java:85) ~[patched_1.13.1.jar:git-Paper-346]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.13.1.jar:git-Paper-346]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.1.jar:git-Paper-346]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:434) ~[patched_1.13.1.jar:git-Paper-346]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.1.jar:git-Paper-346]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.1.jar:git-Paper-346]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
        at me.lewis.inventoryfull.utils.Utils.hologramSend(Utils.java:50) ~[?:?]
        at me.lewis.inventoryfull.events.BreakEvent.onBlockBreak(BreakEvent.java:35) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor811.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.1.jar:git-Paper-346]
        ... 14 more

**Comment by RoboMWM** [comment]
Is there a link to this plugin? Hopefully it's open source.

**Comment by axemwa** [comment]
Ah ok only reason I ask is because it could be an issue with their plugin too where when teleporting to another area with the hologram still trying to trigger in an unloaded chunk or something this part of the error 

`at me.lewis.inventoryfull.utils.Utils.hologramSend(Utils.java:50) ~[?:?]
at me.lewis.inventoryfull.events.BreakEvent.onBlockBreak(BreakEvent.java:35) ~[?:?]`

might show in other plugins aswell if that makes sense

**Comment by RoboMWM** [comment]
Do you have a link to the plugin?

**Comment by axemwa** [comment]
yeah here https://www.spigotmc.org/resources/%E2%9C%98-inventoryfull-%E2%9E%B3-full-customization-holograms-sounds-titles-actionbar-1-8-1-13-1-%E2%9C%98.31544/

**Comment by axemwa** [comment]
seems to hook into holographicdisplays if that means anything too

**Comment by RoboMWM** [comment]
Plugin looks like a total copy of clip's InventoryFull plugin, lol. No wonder I had trouble finding it, doesn't even use the plugin name on the plugin page. Anyways I found the issue, so I'll put in a fix for it now.

**Comment by RoboMWM** [comment]
Fixed, will release soon. Thanks.

**Comment by axemwa** [comment]
Thanks heaps yeah only difference is with inventoryfullplus players can toggle the notification on or off with /invfull toggle command

**Comment by axemwa** [comment]
oh right, was wondering when u plan on releasing the jar and where spigot or dev.bukkit?

**Comment by RoboMWM** [comment]
The update for this plugin or my inventory full plugin?
