### ISSUE TITLE
Players not teleportation.

### ISSUE THREAD

**Issue by MattJG77** [AcmeProject/WildernessTp#48]
player has the permissions. the blindness etc and timer counts down, but then nothing. no actual tp.

```[21:29:53] [Server thread/INFO]: UncleMattJG issued server command: /wild
[21:29:53] [Server thread/INFO]: [WildTP] Wild command called by CraftPlayer{name=UncleMattJG}
[21:29:53] [Server thread/INFO]: [WildTP] Wild teleport called for UncleMattJG for world world
[21:29:53] [Server thread/INFO]: [WildTP] UncleMattJG called /wild args 0
[21:29:53] [Server thread/INFO]: [WildTP] Cooldown check requested for 5d73f1b3-98f6-4e18-9ff5-5db9fbfb42bb
[21:29:53] [Server thread/INFO]: [WildTP] Player has bypass perms
[21:29:54] [Server thread/INFO]: [WildTP] Calling preTeleportEvent
[21:29:54] [Server thread/INFO]: [WildTP] Called preWildTeleportEvent
[21:29:54] [Server thread/INFO]: [WildTP] preping 2 port 2 Location{world=CraftWorld{name=world},x=-1322.0,y=80.0,z=1925.0,pitch=0.0,yaw=0.0}
[21:29:54] [Server thread/INFO]: [WildTP] Teleporting UncleMattJGLocation{world=CraftWorld{name=world},x=-1322.0,y=80.0,z=1925.0,pitch=0.0,yaw=0.0}
[21:29:54] [Craft Scheduler Thread - 23/WARN]: [Wild] Plugin Wild v2.12-9bed641 generated an exception while executing task 218
java.lang.NullPointerException: null
at net.poweredbyhate.wildtp.TeleportGoneWild$4.run(TeleportGoneWild.java:263) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[minecraft_server.jar:git-Spigot-56f8471-7554e08]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [minecraft_server.jar:git-Spigot-56f8471-7554e08]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
[21:29:54] [Server thread/WARN]: [Wild] Task #223 for Wild v2.12-9bed641 generated an exception
java.lang.NoSuchMethodError: org.bukkit.Location.toCenterLocation()Lorg/bukkit/Location;
at net.poweredbyhate.wildtp.TeleportGoneWild.goWild(TeleportGoneWild.java:307) ~[?:?]
at net.poweredbyhate.wildtp.TeleportGoneWild.realTeleportt2(TeleportGoneWild.java:209) ~[?:?]
at net.poweredbyhate.wildtp.TeleportGoneWild.access$700(TeleportGoneWild.java:30) ~[?:?]
at net.poweredbyhate.wildtp.TeleportGoneWild$4$1.call(TeleportGoneWild.java:266) ~[?:?]
at net.poweredbyhate.wildtp.TeleportGoneWild$4$1.call(TeleportGoneWild.java:263) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftFuture.run(CraftFuture.java:88) ~[minecraft_server.jar:git-Spigot-56f8471-7554e08]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [minecraft_server.jar:git-Spigot-56f8471-7554e08]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1022) [minecraft_server.jar:git-Spigot-56f8471-7554e08]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:393) [minecraft_server.jar:git-Spigot-56f8471-7554e08]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:970) [minecraft_server.jar:git-Spigot-56f8471-7554e08]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:815) [minecraft_server.jar:git-Spigot-56f8471-7554e08]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]```

**Comment by MattJG77** [comment]
my config.yml

```debug: true
colldownMsgUseActionBar: true
enableGUI: true
enableBar: true
shareCoolDown: true
callFiremenInNether: true
freezeWhileRTP: false
moveCancelRTP: true
Sound: ENTITY_ENDERMAN_TELEPORT
BlockedBiomes:
- COLD_OCEAN
- DEEP_COLD_OCEAN
- DEEP_FROZEN_OCEAN
- DEEP_LUKEWARM_OCEAN
- DEEP_OCEAN
- DEEP_WARM_OCEAN
- FROZEN_OCEAN
- FROZEN_OCEAN
- LUKEWARM_OCEAN
- OCEAN
- RIVER
- WARM_OCEAN
BlockedBlocks:
- CACTUS
- FIRE
- LAVA
- MAGMA_BLOCK
MinXY: -5000
MaxXY: 5000
movingBorder: false
Wait: 5
Retries: 6
Cooldown: 60
Cost: 0
paidTPconfirmation: 30
teleportNewPlayers: false
dropPlayerFromAbove: false
dropPlayerFromHeight: 255
DoCommands: true
PostCommands:
- title %PLAYER% times 20 100 20
- title %PLAYER% title ["",{"text":"Wilderness","color":"green","bold":false}]
- title %PLAYER% subtitle ["",{"text":"Its too dangerous to go alone.","color":"yellow"}]
useRandomWorlds: false
randomWorlds:
  world: 1337
  world_nether: 42
useGlobalClaimCheck: false
useAlternativeGlobalClaimCheck: false
signTexts:
  createWith: '[wildtp]'
  line1: '&4===================='
  line2: '[&1Wild&0]'
  line3: '&4===================='
  costFree: '&b&lFREE'
  costMoney: '&4%COST% $'
worldsAliaz:
  world: world
  world_nether: world_nether
  world_the_end: world_the_end
overrides: {}
Bypass:
  cooldown:
    COMMAND: false
    GUI: false
    OTHERGUY: true
    PORTAL: false
    SIGN: false
  cost:
    COMMAND: false
    GUI: false
    OTHERGUY: true
    PORTAL: false
    SIGN: false
  delay:
    COMMAND: false
    GUI: false
    OTHERGUY: true
    PORTAL: true
    SIGN: false
Portals:
  Gamemodes:
  - ADVENTURE
  - SURVIVAL
  freezeWhileRTP: false
  moveCancelRTP: true
  xMax: 10
  yMax: 10
  zMax: 10
  push: 1.0
Effects:
  COMMAND:
  - BLINDNESS
  - CONFUSION:99
  - SLOW_DIGGING:3
  GUI: []
  JOIN:
  - BLINDNESS
  - CONFUSION
  OTHERGUY: []
  PORTAL:
  - BLINDNESS
  - CONFUSION
  - INVISIBILITY
  - SLOW:2
  SIGN: []
barColor:
  searching: YELLOW
  waiting: GREEN
barStyle:
  searching: SEGMENTED_6
  waiting: SOLID```

**Comment by RoboMWM** [comment]
Is this issue fixed? You closed this issue

**Comment by MattJG77** [comment]
some how and without doing anything the issue has fixed itself.

**Comment by RoboMWM** [comment]
I'm guessing you either updated the plugin or have upgraded your server to use https://papermc.io

**Comment by MattJG77** [comment]
no, haven't done ether.
could of been a conflicting mod that i removed but i have no idea what or when. perhaps even just a proper server shutdown and restart. i don't know.
