### ISSUE TITLE
Error event was cancelled!

### ISSUE THREAD

**Issue by SrBedrock** [AcmeProject/WildernessTp#50]
I received this error on the console.

```log
>.... [10:39:59 INFO]: Shok3d issued server command: /wild $hut Up And Take My M0ney!
>.... [10:39:59 INFO]: Shok3d issued server command: /wild $hut Up And Take My M0ney!
>.... [10:39:59 INFO]: Shok3d issued server command: /wild $hut Up And Take My M0ney!
>.... [10:39:59 INFO]: Shok3d issued server command: /wild $hut Up And Take My M0ney!
>.... [10:39:59 INFO]: Shok3d issued server command: /wild $hut Up And Take My M0ney!
>.... [10:40:00 INFO]: Shok3d issued server command: /wild $hut Up And Take My M0ney!
>.... [10:23:21 WARN]: java.util.concurrent.ExecutionException: java.lang.Exception: event was cancelled!
>.... [10:23:21 WARN]: at java.util.concurrent.FutureTask.report(FutureTask.java:122)
>.... [10:23:21 WARN]: at java.util.concurrent.FutureTask.get(FutureTask.java:192)
>.... [10:23:21 WARN]: at net.poweredbyhate.wildtp.TeleportGoneWild$4.run(TeleportGoneWild.java:259)
>.... [10:23:21 WARN]: at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
>.... [10:23:21 WARN]: at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
>.... [10:23:21 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
>.... [10:23:21 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>.... [10:23:21 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>.... [10:23:21 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [10:23:21 WARN]: Caused by: java.lang.Exception: event was cancelled!
>.... [10:23:21 WARN]: at net.poweredbyhate.wildtp.RandomLocationSearchTask.call(RandomLocationSearchTask.java:65)
>.... [10:23:21 WARN]: at net.poweredbyhate.wildtp.RandomLocationSearchTask.call(RandomLocationSearchTask.java:21)
>.... [10:23:21 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>.... [10:23:21 WARN]: ... 6 more
```

**Comment by RoboMWM** [comment]
What version are you using?

**Comment by RoboMWM** [comment]
Ok, this error is harmless and is ignored. It occurred because the guy ran the /wild command multiple times in quick succession. Error will be swallowed in next release.
