### ISSUE TITLE
Error executing task on Server java.lang.NullPointerException

### ISSUE THREAD

**Issue by SrBedrock** [AcmeProject/WildernessTp#51]
Error found on console

```log
>.... [21:54:58 INFO]: Viniccius007 issued server command: /wild
>.... [21:55:00 FATAL]: Error executing task on Server
java.lang.NullPointerException: null
at net.minecraft.server.v1_14_R1.ChunkMapDistance.b(ChunkMapDistance.java:245) ~[patched_1.14.4.jar:git-Paper-225]
at net.minecraft.server.v1_14_R1.PlayerChunkMap.movePlayer(PlayerChunkMap.java:1298) ~[patched_1.14.4.jar:git-Paper-225]
at net.minecraft.server.v1_14_R1.ChunkProviderServer.movePlayer(ChunkProviderServer.java:739) ~[patched_1.14.4.jar:git-Paper-225]
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1132) ~[patched_1.14.4.jar:git-Paper-225]
at net.minecraft.server.v1_14_R1.PacketPlayInFlying.a(SourceFile:126) ~[patched_1.14.4.jar:git-Paper-225]
at net.minecraft.server.v1_14_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) ~[patched_1.14.4.jar:git-Paper-225]
at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-225]
at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-225]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-225]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-225]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-225]
at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-225]
at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-225]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-225]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1088) ~[patched_1.14.4.jar:git-Paper-225]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-225]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
>.... [21:55:00 INFO]: Viniccius007 issued server command: /wild $hut Up And Take My M0ney!
```
WildTP Version: Wild version 2.13-8ecba61
Server Version: This server is running Paper version git-Paper-225 (MC: 1.14.4)

**Comment by RoboMWM** [comment]
This doesn't look like an issue with WildTP. Looks like something else that happened asynchronously perhaps.

**Comment by SrBedrock** [comment]
I think it can be ignored because the server shut down due to lack of memory before that.

**Comment by SrBedrock** [comment]
I will pay attention to the log, so far did not happen again.
