### ISSUE TITLE
wildtp.RandomLocationSearchTask invoking autopickup

### ISSUE THREAD

**Issue by SrBedrock** [AcmeProject/WildernessTp#52]
```log
>.... [18:34:28 WARN]: java.lang.IllegalArgumentException: java.lang.ClassCastException@1026493c
>.... [18:34:28 WARN]: at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
>.... [18:34:28 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>.... [18:34:28 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
>.... [18:34:28 WARN]: at com.vk2gpz.autopickup.a.b.b.a.sendPacket(a.java:134)
>.... [18:34:28 WARN]: at com.vk2gpz.autopickup.a.b.b.a.a(a.java:93)
>.... [18:34:28 WARN]: at com.vk2gpz.autopickup.a.b.b.a.sendActionBar(a.java:76)
>.... [18:34:28 WARN]: at com.vk2gpz.autopickup.b.d(b.java:349)
>.... [18:34:28 WARN]: at com.vk2gpz.autopickup.b.c(b.java:335)
>.... [18:34:28 WARN]: at com.vk2gpz.autopickup.b.b(b.java:1342)
>.... [18:34:28 WARN]: at com.vk2gpz.autopickup.e.onBlockBreak(e.java:364)
>.... [18:34:28 WARN]: at sun.reflect.GeneratedMethodAccessor91.invoke(Unknown Source)
>.... [18:34:28 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>.... [18:34:28 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
>.... [18:34:28 WARN]: at com.vk2gpz.autopickup.a.b.m.c.lambda$registerListeners$1(c.java:135)
>.... [18:34:28 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
>.... [18:34:28 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
>.... [18:34:28 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545)
>.... [18:34:28 WARN]: at net.poweredbyhate.wildtp.RandomLocationSearchTask.n0tAGreifClam(RandomLocationSearchTask.java:128)
>.... [18:34:28 WARN]: at net.poweredbyhate.wildtp.RandomLocationSearchTask.chekar(RandomLocationSearchTask.java:101)
>.... [18:34:28 WARN]: at net.poweredbyhate.wildtp.RandomLocationSearchTask.access$000(RandomLocationSearchTask.java:21)
>.... [18:34:28 WARN]: at net.poweredbyhate.wildtp.RandomLocationSearchTask$1.call(RandomLocationSearchTask.java:83)
>.... [18:34:28 WARN]: at net.poweredbyhate.wildtp.RandomLocationSearchTask$1.call(RandomLocationSearchTask.java:80)
>.... [18:34:28 WARN]: at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftFuture.run(CraftFuture.java:88)
>.... [18:34:28 WARN]: at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
>.... [18:34:28 WARN]: at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171)
>.... [18:34:28 WARN]: at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417)
>.... [18:34:28 WARN]: at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098)
>.... [18:34:28 WARN]: at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925)
>.... [18:34:28 WARN]: at java.lang.Thread.run(Thread.java:748)
```
WildTP Version: Wild version 2.13-8ecba61
Server Version: This server is running Paper version git-Paper-225 (MC: 1.14.4)

**Comment by RoboMWM** [comment]
This is not the full stacktrace. Please get the full stacktrace from your log.

**Comment by RoboMWM** [comment]
Also, it's going to be difficult to figure out how to resolve this compatibility issue since his code is obfuscated and behind a paywall, unless you can get him to look at this issue and tell me exactly what he's trying to cast to what from the event.

**Comment by RoboMWM** [comment]
Alternatively, you can use the alternative check instead.

**Comment by SrBedrock** [comment]
I think it can be ignored because the server shut down due to lack of memory before that.

**Comment by SrBedrock** [comment]
I will pay attention to the log, so far did not happen again.

**Comment by SrBedrock** [comment]
```log
>.... [02:11:57 INFO]: Josefinna issued server command: /wild
>.... [02:11:58 INFO]: Josefinna issued server command: /wild $hut Up And Take My M0ney!
>.... [02:11:59 WARN]: java.lang.IllegalArgumentException: java.lang.ClassCastException@7b93d3c1
>.... [02:11:59 WARN]: at sun.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
>.... [02:11:59 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>.... [02:11:59 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
>.... [02:11:59 WARN]: at com.vk2gpz.autopickup.a.b.b.a.sendPacket(a.java:134)
>.... [02:11:59 WARN]: at com.vk2gpz.autopickup.a.b.b.a.a(a.java:93)
>.... [02:11:59 WARN]: at com.vk2gpz.autopickup.a.b.b.a.sendActionBar(a.java:76)
>.... [02:11:59 WARN]: at com.vk2gpz.autopickup.b.d(b.java:349)
>.... [02:11:59 WARN]: at com.vk2gpz.autopickup.b.c(b.java:335)
>.... [02:11:59 WARN]: at com.vk2gpz.autopickup.b.b(b.java:1342)
>.... [02:11:59 WARN]: at com.vk2gpz.autopickup.e.onBlockBreak(e.java:364)
>.... [02:11:59 WARN]: at sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
>.... [02:11:59 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>.... [02:11:59 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
>.... [02:11:59 WARN]: at com.vk2gpz.autopickup.a.b.m.c.lambda$registerListeners$1(c.java:135)
>.... [02:11:59 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
>.... [02:11:59 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
>.... [02:11:59 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545)
>.... [02:11:59 WARN]: at net.poweredbyhate.wildtp.RandomLocationSearchTask.n0tAGreifClam(RandomLocationSearchTask.java:128)
>.... [02:11:59 WARN]: at net.poweredbyhate.wildtp.RandomLocationSearchTask.chekar(RandomLocationSearchTask.java:101)
>.... [02:11:59 WARN]: at net.poweredbyhate.wildtp.RandomLocationSearchTask.access$000(RandomLocationSearchTask.java:21)
>.... [02:11:59 WARN]: at net.poweredbyhate.wildtp.RandomLocationSearchTask$1.call(RandomLocationSearchTask.java:83)
>.... [02:11:59 WARN]: at net.poweredbyhate.wildtp.RandomLocationSearchTask$1.call(RandomLocationSearchTask.java:80)
>.... [02:11:59 WARN]: at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftFuture.run(CraftFuture.java:88)
>.... [02:11:59 WARN]: at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
>.... [02:11:59 WARN]: at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171)
>.... [02:11:59 WARN]: at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417)
>.... [02:11:59 WARN]: at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098)
>.... [02:11:59 WARN]: at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925)
>.... [02:11:59 WARN]: at java.lang.Thread.run(Thread.java:748)
```

**Comment by RoboMWM** [comment]
> Also, it's going to be difficult to figure out how to resolve this compatibility issue since his code is obfuscated and behind a paywall, unless you can get him to look at this issue and tell me exactly what he's trying to cast to what from the event.



> Alternatively, you can use the alternative check instead.

Not much more I can say here otherwise. Disable the global check and enable the alternative check. 

You'll need to get vk2gpz to let me know what his plugin is choking on. I'm gonna guess his plugin is trying to invoke something in Player. If he can either open source his code (the best way) or at least let me know which method he's invoking and what result he's expecting then we can resolve this. Otherwise there's nothing I can do.

**Comment by RoboMWM** [comment]
> Disable the global check and enable the alternative check.

This is the solution for you btw.

**Comment by RoboMWM** [comment]
He's trying to send the player an actionbar message but that won't work cuz it's a fake player. At least that's my guess looking at his obfuscated package names.
