### ISSUE TITLE
rtp cooldown error

### ISSUE THREAD

**Issue by GamerOfEnder** [AcmeProject/WildernessTp#54]
Hey, this plugin is just amazing but i got this issue after trying as a normal player to rtp before the cooldown set:
```
[18:03:05] [Server thread/INFO]: GamerOfEnder issued server command: /rtp
[18:03:05] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'rtp' in plugin Wild v2.13-8ecba61
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot.jar:git-Spigot-56f8471-ccd47a5]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot.jar:git-Spigot-56f8471-ccd47a5]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:710) ~[spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1641) ~[spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1481) ~[spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:103) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:885) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.sendActionBar(Ljava/lang/String;)V
	at net.poweredbyhate.wildtp.TeleportGoneWild.cook(TeleportGoneWild.java:150) ~[?:?]
	at net.poweredbyhate.wildtp.TeleportGoneWild.WildTeleport(TeleportGoneWild.java:64) ~[?:?]
	at net.poweredbyhate.wildtp.TeleportGoneWild.WildTeleport(TeleportGoneWild.java:60) ~[?:?]
	at net.poweredbyhate.wildtp.CommandsGoneWild.onCommand(CommandsGoneWild.java:43) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot.jar:git-Spigot-56f8471-ccd47a5]
	... 17 more
[18:03:25] [Server thread/INFO]: GamerOfEnder issued server command: /rtp
[18:03:25] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'rtp' in plugin Wild v2.13-8ecba61
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot.jar:git-Spigot-56f8471-ccd47a5]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot.jar:git-Spigot-56f8471-ccd47a5]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:710) ~[spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1641) ~[spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1481) ~[spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:886) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.sendActionBar(Ljava/lang/String;)V
	at net.poweredbyhate.wildtp.TeleportGoneWild.cook(TeleportGoneWild.java:150) ~[?:?]
	at net.poweredbyhate.wildtp.TeleportGoneWild.WildTeleport(TeleportGoneWild.java:64) ~[?:?]
	at net.poweredbyhate.wildtp.TeleportGoneWild.WildTeleport(TeleportGoneWild.java:60) ~[?:?]
	at net.poweredbyhate.wildtp.CommandsGoneWild.onCommand(CommandsGoneWild.java:43) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot.jar:git-Spigot-56f8471-ccd47a5]
	... 17 more
```
Thanks in advance for help !

**Comment by RoboMWM** [comment]
Either wait for the next update or switch to [Paper](https://papermc.io) as I've fixed this but haven't released it yet.

**Comment by GamerOfEnder** [comment]
And can you tell me, please, wen you'll release this update ?

**Comment by RoboMWM** [comment]
after I address a few other bug reports.

I highly recommend switching to Paper regardless.

**Comment by RoboMWM** [comment]
after I address a few other bug reports.
